version: "3.1"
 
services:
  app:
    build: .
    restart: always
    ports: 
      - "8080:8080"
    depends_on:
      - db
 
  db:
    image: mongo
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./data:/data/db
    ports:
      - "27017:27017"
    restart: always
